export const countriesAr = {
  "Afghanistan": "أفغانستان",
  "Albania": "ألبانيا",
  "Algeria": "الجزائر",
  "Andorra": "أندورا",
  "Angola": "أنغولا",
  "Antigua and Barbuda": "أنتيغوا وباربودا",
  "Argentina": "الأرجنتين",
  "Armenia": "أرمينيا",
  "Australia": "أستراليا",
  "Austria": "النمسا",
  "Azerbaijan": "أذربيجان",
  "Bahamas": "البهاما",
  "Bahrain": "البحرين",
  "Bangladesh": "بنغلاديش",
  "Barbados": "باربادوس",
  "Belarus": "بيلاروسيا",
  "Belgium": "بلجيكا",
  "Belize": "بليز",
  "Benin": "بنين",
  "Bhutan": "بوتان",
  "Bolivia": "بوليفيا",
  "Bosnia and Herzegovina": "البوسنة والهرسك",
  "Botswana": "بوتسوانا",
  "Brazil": "البرازيل",
  "Brunei": "بروناي",
  "Bulgaria": "بلغاريا",
  "Burkina Faso": "بوركينا فاسو",
  "Burundi": "بوروندي",
  "Cambodia": "كمبوديا",
  "Cameroon": "الكاميرون",
  "Canada": "كندا",
  "Cape Verde": "الرأس الأخضر",
  "Central African Republic": "جمهورية أفريقيا الوسطى",
  "Chad": "تشاد",
  "Chile": "تشيلي",
  "China": "الصين",
  "Colombia": "كولومبيا",
  "Comoros": "جزر القمر",
  "Costa Rica": "كوستاريكا",
  "Côte d’Ivoire": "ساحل العاج",
  "Croatia": "كرواتيا",
  "Cuba": "كوبا",
  "Cyprus": "قبرص",
  "Czech Republic": "التشيك",
  "Czechia": "التشيك",
  "Democratic Republic of the Congo": "جمهورية الكونغو الديمقراطية",
  "Denmark": "الدنمارك",
  "Djibouti": "جيبوتي",
  "Dominica": "دومينيكا",
  "Dominican Republic": "جمهورية الدومينيكان",
  "East Timor": "تيمور الشرقية",
  "Ecuador": "الإكوادور",
  "Egypt": "مصر",
  "El Salvador": "السلفادور",
  "Equatorial Guinea": "غينيا الاستوائية",
  "Eritrea": "إريتريا",
  "Estonia": "إستونيا",
  "Ethiopia": "إثيوبيا",
  "Fiji": "فيجي",
  "Finland": "فنلندا",
  "France": "فرنسا",
  "Gabon": "الغابون",
  "Gambia": "غامبيا",
  "Georgia": "جورجيا",
  "Germany": "ألمانيا",
  "Ghana": "غانا",
  "Greece": "اليونان",
  "Grenada": "جرينادا",
  "Guatemala": "غواتيمالا",
  "Guinea": "غينيا",
  "Guinea-Bissau": "غينيا بيساو",
  "Guyana": "غويانا",
  "Haiti": "هايتي",
  "Honduras": "هندوراس",
  "Hungary": "المجر",
  "Iceland": "آيسلندا",
  "India": "الهند",
  "Indonesia": "إندونيسيا",
  "Iran": "إيران",
  "Iraq": "العراق",
  "Ireland": "جمهورية أيرلندا",
  "Israel": "إسرائيل",
  "Italy": "إيطاليا",
  "Jamaica": "جامايكا",
  "Japan": "اليابان",
  "Jordan": "الأردن",
  "Kazakhstan": "كازاخستان",
  "Kenya": "كينيا",
  "Kiribati": "كيريباتي",
  "Kuwait": "الكويت",
  "Kyrgyzstan": "قرغيزستان",
  "Laos": "لاوس",
  "Latvia": "لاتفيا",
  "Lebanon": "لبنان",
  "Lesotho": "ليسوتو",
  "Liberia": "ليبيريا",
  "Libya": "ليبيا",
  "Liechtenstein": "ليختنشتاين",
  "Lithuania": "ليتوانيا",
  "Luxembourg": "لوكسمبورغ",
  "Madagascar": "مدغشقر",
  "Malawi": "مالاوي",
  "Malaysia": "ماليزيا",
  "Maldives": "جزر المالديف",
  "Mali": "مالي",
  "Malta": "مالطا",
  "Marshall Islands": "جزر مارشال",
  "Mauritania": "موريتانيا",
  "Mauritius": "موريشيوس",
  "Mexico": "المكسيك",
  "Micronesia": "مايكرونيزيا",
  "Moldova": "مولدوفا",
  "Monaco": "موناكو",
  "Mongolia": "منغوليا",
  "Montenegro": "الجبل الأسود",
  "Morocco": "المغرب",
  "Mozambique": "موزمبيق",
  "Myanmar": "بورما",
  "Namibia": "ناميبيا",
  "Nauru": "ناورو",
  "Nepal": "نيبال",
  "Netherlands": "هولندا",
  "New Zealand": "نيوزيلندا",
  "Nicaragua": "نيكاراجوا",
  "Niger": "النيجر",
  "Nigeria": "نيجيريا",
  "North Korea": "كوريا الشمالية",
  "Norway": "النرويج",
  "Oman": "سلطنة عمان",
  "Pakistan": "باكستان",
  "Palau": "بالاو",
  "Panama": "بنما",
  "Papua New Guinea": "بابوا غينيا الجديدة",
  "Paraguay": "باراغواي",
  "Peru": "بيرو",
  "Philippines": "الفلبين",
  "Poland": "بولندا",
  "Portugal": "البرتغال",
  "Qatar": "قطر",
  "Republic of the Congo": "جمهورية الكونغو",
  "Republic of Macedonia": "جمهورية مقدونيا",
  "Romania": "رومانيا",
  "Russia": "روسيا",
  "Rwanda": "رواندا",
  "Saint Kitts and Nevis": "سانت كيتس ونيفيس",
  "Saint Lucia": "سانت لوسيا",
  "Saint Vincent and the Grenadines": "سانت فنسينت والجرينادينز",
  "Samoa": "ساموا",
  "San Marino": "سان مارينو",
  "Sao Tome and Principe": "ساو تومي وبرينسيب",
  "Saudi Arabia": "السعودية",
  "Senegal": "السنغال",
  "Serbia": "صربيا",
  "Seychelles": "سيشيل",
  "Sierra Leone": "سيراليون",
  "Singapore": "سنغافورة",
  "Slovakia": "سلوفاكيا",
  "Slovenia": "سلوفينيا",
  "Solomon Islands": "جزر سليمان",
  "Somalia": "الصومال",
  "South Africa": "جنوب أفريقيا",
  "South Korea": "كوريا الجنوبية",
  "South Sudan": "جنوب السودان",
  "Spain": "إسبانيا",
  "Sri Lanka": "سريلانكا",
  "Sudan": "السودان",
  "Suriname": "سورينام",
  "Swaziland": "سوازيلاند",
  "Sweden": "السويد",
  "Switzerland": "سويسرا",
  "Syria": "سوريا",
  "Tajikistan": "طاجيكستان",
  "Tanzania": "تنزانيا",
  "Thailand": "تايلاند",
  "Togo": "توغو",
  "Tonga": "تونجا",
  "Trinidad and Tobago": "ترينيداد وتوباغو",
  "Tunisia": "تونس",
  "Turkey": "تركيا",
  "Turkmenistan": "تركمانستان",
  "Tuvalu": "توفالو",
  "Uganda": "أوغندا",
  "Ukraine": "أوكرانيا",
  "United Arab Emirates": "الإمارات العربية المتحدة",
  "United Kingdom": "المملكة المتحدة",
  "US": "الولايات المتحدة",
  "Uruguay": "أوروغواي",
  "Uzbekistan": "أوزبكستان",
  "Vanuatu": "فانواتو",
  "Venezuela": "فنزويلا",
  "Vietnam": "فيتنام",
  "Yemen": "اليمن",
  "Zambia": "زامبيا",
  "Zimbabwe": "زيمبابوي",
  "Diamond Princess": "السفينة دايموند برنسس",
  "North Macedonia": "شمال مقدونيا",
  "Cote d'Ivoire": "ساحل العاج",
  "West Bank and Gaza": "الضفة الغربية وقطاع غزة",
  "Congo (Kinshasa)": "الكونغو-كينشاسا",
  "Congo (Brazzaville)": "الكونغو-برازافيل",
  "Burma": "بورما",
  "Eswatini": "إسواتيني",
  "MS Zaandam": "السفينة إم إس زاندام",
  "Holy See": "الكرسي البابوي",
  "Cabo Verde": "الرأس الأخضر",
  "Timor-Leste": "جمهورية تيمور الشرقية الديمقراطية",
  "Korea, South": "جمهورية كوريا",
  "Kosovo": "كوسوفو",
  "Taiwan*": "تايوان",
  "Western Sahara": "الصحراء الغربية",
};

export const iso2 = {
  Afghanistan: "AF",
  "Aland Islands": "AX",
  Albania: "AL",
  Algeria: "DZ",
  "American Samoa": "AS",
  Andorra: "AD",
  Angola: "AO",
  Anguilla: "AI",
  Antarctica: "AQ",
  "Antigua and Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bonaire, Saint Eustatius and Saba ": "BQ",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  "Bouvet Island": "BV",
  Brazil: "BR",
  "British Indian Ocean Territory": "IO",
  "British Virgin Islands": "VG",
  Brunei: "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  "Christmas Island": "CX",
  "Cocos Islands": "CC",
  Colombia: "CO",
  Comoros: "KM",
  "Cook Islands": "CK",
  "Costa Rica": "CR",
  Croatia: "HR",
  Cuba: "CU",
  Curacao: "CW",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  "Democratic Republic of the Congo": "CD",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  "East Timor": "TL",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Estonia: "EE",
  Ethiopia: "ET",
  "Falkland Islands": "FK",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  "French Southern Territories": "TF",
  Gabon: "GA",
  "Gambia, The": "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernsey: "GG",
  "Guinea-Bissau": "GW",
  Guinea: "GN",
  Guyana: "GY",
  Haiti: "HT",
  "Heard Island and McDonald Islands": "HM",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  "Isle of Man": "IM",
  Israel: "IL",
  Italy: "IT",
  "Ivory Coast": "CI",
  Jamaica: "JM",
  Japan: "JP",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KI",
  "Korea, South": "KR",
  Kosovo: "XK",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macao: "MO",
  Macedonia: "MK",
  Madagascar: "MG",
  "Mainland China": "CN",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  "Marshall Islands": "MH",
  Martinique: "MQ",
  Mauritania: "MR",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  Micronesia: "FM",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Montserrat: "MS",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  Niue: "NU",
  "Norfolk Island": "NF",
  "Northern Mariana Islands": "MP",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  "Palestinian Territory": "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  "People's Republic of Korea": "KP",
  Peru: "PE",
  Philippines: "PH",
  Pitcairn: "PN",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  "Republic of the Congo": "CG",
  Reunion: "RE",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  "Saint Barthelemy": "BL",
  "Saint Helena": "SH",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Martin": "MF",
  "Saint Pierre and Miquelon": "PM",
  "Saint Vincent and the Grenadines": "VC",
  Samoa: "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  "Sint Maarten": "SX",
  Slovakia: "SK",
  Slovenia: "SI",
  "Solomon Islands": "SB",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Georgia and the South Sandwich Islands": "GS",
  "South Sudan": "SS",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Suriname: "SR",
  "Svalbard and Jan Mayen": "SJ",
  Swaziland: "SZ",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  "Taiwan*": "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  "Turks and Caicos Islands": "TC",
  Tuvalu: "TV",
  "U.S. Virgin Islands": "VI",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States Minor Outlying Islands": "UM",
  Uruguay: "UY",
  US: "US",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  Vatican: "VA",
  Venezuela: "VE",
  Vietnam: "VN",
  "Wallis and Futuna": "WF",
  "Western Sahara": "EH",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW"
};
